# Generated by Django 4.2 on 2024-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0016_alter_attendance_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('total_active_members', models.PositiveIntegerField(default=0)),
                ('total_inactive_members', models.PositiveIntegerField(default=0)),
                ('total_active_pricing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_inactive_pricing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
