# Generated by Django 4.2 on 2024-11-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0018_rename_total_active_members_membershipreport_active_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipReport',
        ),
    ]
